server:
  port: 8088
  servlet:
    path: "*.do"
logging:
  level:
    com.ws: debug
    org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.01:3306/app_versions
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.ws.bean

    #mapper-locations: mapper/*.xml

